### PR TITLE
bulk attendance functionality

### PR DESCRIPTION
**Pull request by nahloo-obi**
As Product Owner, I want the system to allow bulk operations for registering the attendance of all students in a lesson to improve speed and efficiency of the attendance management process.

### CODE REVIEW

**Review by Umer-shahzad1 — COMMENTED** [review]
The functionality for bulk attendance seems to be working correctly. looks ok

**Review by asmaUsman — COMMENTED** [review]
do we need to add O for notified absent in bulk ?

**Comment by asmaUsman** [comment]
do we need here to add o for notified absent? @nahloo-obi @OCE1960 @Rozmin12 @Umer-shahzad1

**Review by Rozmin12 — COMMENTED** [review]
The attendance status does work!

**Review by OCE1960 — APPROVED** [review]

**Pull request merged**
